server:
  port: 9090

#数据库
spring:
  application:
    name: chapter4-Druid #微服务唯一标识，总是放在第一行
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.32.85:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&failOverReadOnly=false&secondsBeforeRetryMaster=0&queriesBeforeRetryMaster=0
    username: root
    password: roottest

    #增加druid的配置
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j


  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true



  aop:
    proxy-target-class: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss



  #控制台输出的json更加美观
  jackson:
    serialization:
      indent_output: true





logging:
  file: ${spring.application.name}.log

#访问Druid的帐号和密码
druid:
  loginUsername: druid
  loginPassword: 123456
  allow: 127.0.0.1 #白名单
  deny: 192.168.0.99 #黑名单
  resetEnable: false #是否重置数据
  exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  #忽略路径